valid_formats = {
    'shapefile':'shapefile',
    'shp':'shapefile',
    '.shp':'shapefile',
    'esri shapefile':'shapefile',
    'esri':'shapefile',
    'esri shp':'shapefile',
    'geojson':'geojson',
    'geo json':'geojson',
    '.geojson':'geojson',
    'gjson':'geojson',
    'geopackage':'geopackage',
    'gpkg':'geopackage',
    '.geopackage':'geopackage',
    '.gpkg':'geopackage',
    'geopaczka':'geopackage',
    'csv':'csv',
    '.csv':'csv',
    'comma-separated values':'csv',
    'comma separated values': 'csv',
    'topojson':'topojson',
    'topo json':'topojson',
    '.topojson':'topojson',
    'tjson':'topojson',
    'topology json':'topojson',
    'gml':'gml',
    '.gml':'gml',
    'geography markup language':'gml'
    }